// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  about: defineAsyncComponent(() => import("./About/index.vue")),
  big_wordz: defineAsyncComponent(() => import("./BigWordz/index.vue")),
  intro_text: defineAsyncComponent(() => import("./IntroText/index.vue")),
  pif_paf: defineAsyncComponent(() => import("./PifPaf/index.vue")),
  projects_list: defineAsyncComponent(() => import("./ProjectsList/index.vue")),
  rich_text: defineAsyncComponent(() => import("./RichText/index.vue")),
  skills: defineAsyncComponent(() => import("./Skills/index.vue")),
});
